# Generated by Django 2.2.3 on 2020-03-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.Game'),
            preserve_default=False,
        ),
    ]
